//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passara.Core.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Passara.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passara.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string Button_Lock {
            get {
                return ResourceManager.GetString("Button_Lock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string Button_Unlock {
            get {
                return ResourceManager.GetString("Button_Unlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Biometric authentication failed.
        /// </summary>
        internal static string Error_BiometricFailed {
            get {
                return ResourceManager.GetString("Error_BiometricFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decryption failed. Invalid password or corrupted data.
        /// </summary>
        internal static string Error_DecryptionFailed {
            get {
                return ResourceManager.GetString("Error_DecryptionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disk full. Cannot save data.
        /// </summary>
        internal static string Error_DiskFull {
            get {
                return ResourceManager.GetString("Error_DiskFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encryption failed.
        /// </summary>
        internal static string Error_EncryptionFailed {
            get {
                return ResourceManager.GetString("Error_EncryptionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid master password.
        /// </summary>
        internal static string Error_InvalidMasterPassword {
            get {
                return ResourceManager.GetString("Error_InvalidMasterPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network error. Please check your connection.
        /// </summary>
        internal static string Error_NetworkError {
            get {
                return ResourceManager.GetString("Error_NetworkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        internal static string Error_None {
            get {
                return ResourceManager.GetString("Error_None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string Error_PermissionDenied {
            get {
                return ResourceManager.GetString("Error_PermissionDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.
        /// </summary>
        internal static string Error_SyncFailed {
            get {
                return ResourceManager.GetString("Error_SyncFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Too many failed attempts. Please try again later.
        /// </summary>
        internal static string Error_TooManyFailedAttempts {
            get {
                return ResourceManager.GetString("Error_TooManyFailedAttempts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vault already exists.
        /// </summary>
        internal static string Error_VaultAlreadyExists {
            get {
                return ResourceManager.GetString("Error_VaultAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vault file is corrupted.
        /// </summary>
        internal static string Error_VaultCorrupted {
            get {
                return ResourceManager.GetString("Error_VaultCorrupted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vault is locked.
        /// </summary>
        internal static string Error_VaultLocked {
            get {
                return ResourceManager.GetString("Error_VaultLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vault not found.
        /// </summary>
        internal static string Error_VaultNotFound {
            get {
                return ResourceManager.GetString("Error_VaultNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UntitledEntry {
            get {
                return ResourceManager.GetString("UntitledEntry", resourceCulture);
            }
        }
    }
}
